services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - passion-meet-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  passion-meet-db:
